version: '3'

services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    working_dir: /application
    ports:
      - "8082:8082"
    networks:
      expose_network:
    restart: always

networks:
  # Join proxy network for exposing http services
  expose_network:
    external:
      name: web_proxy
